name: Deploy BEdita

on:
  push:
    branches:
      - main
    paths-ignore:
      - manager/**

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: 'eu-south-1'
  ECS_CLUSTER: 'dreamteam'

jobs:
  deploy:
    uses: ./.github/workflows/bedita-deploy.yml
    strategy:
      matrix:
        environment: ['Production', 'Development']
    with:
      environment: ${{ matrix.environment }}
      region: ${{ env.AWS_REGION }}
      cluster: ${{ env.ECS_CLUSTER }}
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.environment }}
      cancel-in-progress: true
