name: Deploy BEdita from PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - manager/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/bedita-deploy.yml
    with:
      AWS_REGION: 'eu-south-1'
      ECS_CLUSTER: 'dreamteam'
      ENV_NAME: 'Development'
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-Development
      cancel-in-progress: true
