name: Deploy BEdita

on:
  push:
    branches:
      - main
    paths-ignore:
      - manager/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/bedita-deploy.yml
    strategy:
      matrix:
        environment: ['Production', 'Development']
    with:
      AWS_REGION: 'eu-south-1'
      ECS_CLUSTER: 'dreamteam'
      ECS_SERVICE: ${{ vars.ECS_SERVICE }}
      ENV_NAME: ${{ matrix.environment }}
    secrets: inherit
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.environment }}
      cancel-in-progress: true
