name: 'JS/CSS'

on:
  pull_request: {}
  push: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          token: ${{ secrets.NPM_TOKEN }}
          cache: yarn
      - name: Install project dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
