name: Deploy Manager

on:
  push:
    branches:
      - main
    paths:
      - manager/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/bedita-deploy.yml
    strategy:
      matrix:
        environment: ['Production', 'Development']
    with:
      environment: ${{ matrix.environment }}
      region: 'eu-south-1'
      cluster: 'dreamteam'
    secrets: inherit
    concurrency:
      group: manager-${{ github.workflow }}-${{ github.ref }}-${{ matrix.environment }}
      cancel-in-progress: true
