name: Deploy Manager

on:
  pull_request:
    branches:
      - main
    paths:
      - manager/**

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/bedita-deploy.yml
    with:
      AWS_REGION: 'eu-south-1'
      ECS_CLUSTER: 'dreamteam'
      ECS_SERVICE: ${{ vars.ECS_SERVICE }}
      ENV_NAME: 'Development'
      ENV_URL: ${{ vars.ENV_URL }}
      TASK_FILE: ${{ vars.TASK_FILE }}
    secrets: inherit
    concurrency:
      group: manager-${{ github.workflow }}-${{ github.ref }}-Development
      cancel-in-progress: true
